export const CHANGE_TOPIC = 'CHANGE_TOPIC';
export const INITIALISE = 'INITIALISE';
export const SET_TOPIC_DATA = 'SET_TOPIC_DATA';
export const SET_SUBTOPIC_DATA = 'SET_SUBTOPIC_DATA';
export const SET_SUBTOPIC_STORIES = 'SET_SUBTOPIC_STORIES';
export const UPDATE_SUBTOPIC_STATUS = 'UPDATE_SUBTOPIC_STATUS';
export const UPDATE_STORY_STATUS = 'UPDATE_STORY_STATUS';